"""
    qhook API

    Lightweight event gateway with built-in queue, retry, and workflow engine.  qhook receives webhooks and events via HTTP, queues them, and delivers to configured handlers with retry and dead-letter support.  All responses include an `X-API-Version` header indicating the current API version. 

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import warnings
from pydantic import validate_call, Field, StrictFloat, StrictStr, StrictInt
from typing import Any, Dict, List, Optional, Tuple, Union
from typing_extensions import Annotated

from pydantic import Field, StrictStr, field_validator
from typing import Any, Dict, Optional
from typing_extensions import Annotated
from qhook_client.models.receive_webhook200_response import ReceiveWebhook200Response
from qhook_client.models.send_event202_response import SendEvent202Response
from qhook_client.models.sns_message import SnsMessage

from qhook_client.api_client import ApiClient, RequestSerialized
from qhook_client.api_response import ApiResponse
from qhook_client.rest import RESTResponseType


class IngestApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client


    @validate_call
    def receive_sns(
        self,
        source: Annotated[StrictStr, Field(description="Source name as defined in qhook configuration")],
        sns_message: SnsMessage,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> str:
        """Receive an AWS SNS message

        Receives AWS SNS messages (Notification, SubscriptionConfirmation, UnsubscribeConfirmation). Subscription confirmations are auto-confirmed. Notification payloads are unwrapped from the SNS envelope and processed as events.  X.509 signature verification is performed unless `skip_verify: true` is set on the source. 

        :param source: Source name as defined in qhook configuration (required)
        :type source: str
        :param sns_message: (required)
        :type sns_message: SnsMessage
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._receive_sns_serialize(
            source=source,
            sns_message=sns_message,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "str",
            '400': "str",
            '401': "str",
            '404': "str",
            '413': None,
            '429': None,
            '500': "str",
            '503': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def receive_sns_with_http_info(
        self,
        source: Annotated[StrictStr, Field(description="Source name as defined in qhook configuration")],
        sns_message: SnsMessage,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[str]:
        """Receive an AWS SNS message

        Receives AWS SNS messages (Notification, SubscriptionConfirmation, UnsubscribeConfirmation). Subscription confirmations are auto-confirmed. Notification payloads are unwrapped from the SNS envelope and processed as events.  X.509 signature verification is performed unless `skip_verify: true` is set on the source. 

        :param source: Source name as defined in qhook configuration (required)
        :type source: str
        :param sns_message: (required)
        :type sns_message: SnsMessage
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._receive_sns_serialize(
            source=source,
            sns_message=sns_message,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "str",
            '400': "str",
            '401': "str",
            '404': "str",
            '413': None,
            '429': None,
            '500': "str",
            '503': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def receive_sns_without_preload_content(
        self,
        source: Annotated[StrictStr, Field(description="Source name as defined in qhook configuration")],
        sns_message: SnsMessage,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Receive an AWS SNS message

        Receives AWS SNS messages (Notification, SubscriptionConfirmation, UnsubscribeConfirmation). Subscription confirmations are auto-confirmed. Notification payloads are unwrapped from the SNS envelope and processed as events.  X.509 signature verification is performed unless `skip_verify: true` is set on the source. 

        :param source: Source name as defined in qhook configuration (required)
        :type source: str
        :param sns_message: (required)
        :type sns_message: SnsMessage
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._receive_sns_serialize(
            source=source,
            sns_message=sns_message,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "str",
            '400': "str",
            '401': "str",
            '404': "str",
            '413': None,
            '429': None,
            '500': "str",
            '503': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _receive_sns_serialize(
        self,
        source,
        sns_message,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if source is not None:
            _path_params['source'] = source
        # process the query parameters
        # process the header parameters
        # process the form parameters
        # process the body parameter
        if sns_message is not None:
            _body_params = sns_message


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'text/plain'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/sns/{source}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def receive_webhook(
        self,
        source: Annotated[StrictStr, Field(description="Source name as defined in qhook configuration")],
        request_body: Dict[str, Any],
        x_hub_signature_256: Annotated[Optional[StrictStr], Field(description="GitHub HMAC-SHA256 signature")] = None,
        stripe_signature: Annotated[Optional[StrictStr], Field(description="Stripe signature with timestamp")] = None,
        x_shopify_hmac_sha256: Annotated[Optional[StrictStr], Field(description="Shopify Base64-encoded HMAC-SHA256")] = None,
        ce_type: Annotated[Optional[StrictStr], Field(description="CloudEvents event type (overrides provider-specific extraction)")] = None,
        ce_specversion: Annotated[Optional[StrictStr], Field(description="CloudEvents spec version")] = None,
        ce_source: Annotated[Optional[StrictStr], Field(description="CloudEvents source URI")] = None,
        ce_id: Annotated[Optional[StrictStr], Field(description="CloudEvents event ID")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ReceiveWebhook200Response:
        """Receive a webhook

        Receives a webhook payload from an external provider (e.g. GitHub, Stripe, Shopify). Signature verification is performed if configured for the source.  **Event type extraction order:** 1. `ce-type` header (CloudEvents binary mode) 2. `type` field in JSON body (CloudEvents structured mode) 3. Provider-specific logic (Stripe `$.type`, GitHub `$.action`, Shopify `$.topic`) 4. Fallback: `\"event\"` 

        :param source: Source name as defined in qhook configuration (required)
        :type source: str
        :param request_body: (required)
        :type request_body: Dict[str, object]
        :param x_hub_signature_256: GitHub HMAC-SHA256 signature
        :type x_hub_signature_256: str
        :param stripe_signature: Stripe signature with timestamp
        :type stripe_signature: str
        :param x_shopify_hmac_sha256: Shopify Base64-encoded HMAC-SHA256
        :type x_shopify_hmac_sha256: str
        :param ce_type: CloudEvents event type (overrides provider-specific extraction)
        :type ce_type: str
        :param ce_specversion: CloudEvents spec version
        :type ce_specversion: str
        :param ce_source: CloudEvents source URI
        :type ce_source: str
        :param ce_id: CloudEvents event ID
        :type ce_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._receive_webhook_serialize(
            source=source,
            request_body=request_body,
            x_hub_signature_256=x_hub_signature_256,
            stripe_signature=stripe_signature,
            x_shopify_hmac_sha256=x_shopify_hmac_sha256,
            ce_type=ce_type,
            ce_specversion=ce_specversion,
            ce_source=ce_source,
            ce_id=ce_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ReceiveWebhook200Response",
            '400': "str",
            '401': "str",
            '404': "str",
            '413': None,
            '429': None,
            '500': "str",
            '503': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def receive_webhook_with_http_info(
        self,
        source: Annotated[StrictStr, Field(description="Source name as defined in qhook configuration")],
        request_body: Dict[str, Any],
        x_hub_signature_256: Annotated[Optional[StrictStr], Field(description="GitHub HMAC-SHA256 signature")] = None,
        stripe_signature: Annotated[Optional[StrictStr], Field(description="Stripe signature with timestamp")] = None,
        x_shopify_hmac_sha256: Annotated[Optional[StrictStr], Field(description="Shopify Base64-encoded HMAC-SHA256")] = None,
        ce_type: Annotated[Optional[StrictStr], Field(description="CloudEvents event type (overrides provider-specific extraction)")] = None,
        ce_specversion: Annotated[Optional[StrictStr], Field(description="CloudEvents spec version")] = None,
        ce_source: Annotated[Optional[StrictStr], Field(description="CloudEvents source URI")] = None,
        ce_id: Annotated[Optional[StrictStr], Field(description="CloudEvents event ID")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[ReceiveWebhook200Response]:
        """Receive a webhook

        Receives a webhook payload from an external provider (e.g. GitHub, Stripe, Shopify). Signature verification is performed if configured for the source.  **Event type extraction order:** 1. `ce-type` header (CloudEvents binary mode) 2. `type` field in JSON body (CloudEvents structured mode) 3. Provider-specific logic (Stripe `$.type`, GitHub `$.action`, Shopify `$.topic`) 4. Fallback: `\"event\"` 

        :param source: Source name as defined in qhook configuration (required)
        :type source: str
        :param request_body: (required)
        :type request_body: Dict[str, object]
        :param x_hub_signature_256: GitHub HMAC-SHA256 signature
        :type x_hub_signature_256: str
        :param stripe_signature: Stripe signature with timestamp
        :type stripe_signature: str
        :param x_shopify_hmac_sha256: Shopify Base64-encoded HMAC-SHA256
        :type x_shopify_hmac_sha256: str
        :param ce_type: CloudEvents event type (overrides provider-specific extraction)
        :type ce_type: str
        :param ce_specversion: CloudEvents spec version
        :type ce_specversion: str
        :param ce_source: CloudEvents source URI
        :type ce_source: str
        :param ce_id: CloudEvents event ID
        :type ce_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._receive_webhook_serialize(
            source=source,
            request_body=request_body,
            x_hub_signature_256=x_hub_signature_256,
            stripe_signature=stripe_signature,
            x_shopify_hmac_sha256=x_shopify_hmac_sha256,
            ce_type=ce_type,
            ce_specversion=ce_specversion,
            ce_source=ce_source,
            ce_id=ce_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ReceiveWebhook200Response",
            '400': "str",
            '401': "str",
            '404': "str",
            '413': None,
            '429': None,
            '500': "str",
            '503': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def receive_webhook_without_preload_content(
        self,
        source: Annotated[StrictStr, Field(description="Source name as defined in qhook configuration")],
        request_body: Dict[str, Any],
        x_hub_signature_256: Annotated[Optional[StrictStr], Field(description="GitHub HMAC-SHA256 signature")] = None,
        stripe_signature: Annotated[Optional[StrictStr], Field(description="Stripe signature with timestamp")] = None,
        x_shopify_hmac_sha256: Annotated[Optional[StrictStr], Field(description="Shopify Base64-encoded HMAC-SHA256")] = None,
        ce_type: Annotated[Optional[StrictStr], Field(description="CloudEvents event type (overrides provider-specific extraction)")] = None,
        ce_specversion: Annotated[Optional[StrictStr], Field(description="CloudEvents spec version")] = None,
        ce_source: Annotated[Optional[StrictStr], Field(description="CloudEvents source URI")] = None,
        ce_id: Annotated[Optional[StrictStr], Field(description="CloudEvents event ID")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Receive a webhook

        Receives a webhook payload from an external provider (e.g. GitHub, Stripe, Shopify). Signature verification is performed if configured for the source.  **Event type extraction order:** 1. `ce-type` header (CloudEvents binary mode) 2. `type` field in JSON body (CloudEvents structured mode) 3. Provider-specific logic (Stripe `$.type`, GitHub `$.action`, Shopify `$.topic`) 4. Fallback: `\"event\"` 

        :param source: Source name as defined in qhook configuration (required)
        :type source: str
        :param request_body: (required)
        :type request_body: Dict[str, object]
        :param x_hub_signature_256: GitHub HMAC-SHA256 signature
        :type x_hub_signature_256: str
        :param stripe_signature: Stripe signature with timestamp
        :type stripe_signature: str
        :param x_shopify_hmac_sha256: Shopify Base64-encoded HMAC-SHA256
        :type x_shopify_hmac_sha256: str
        :param ce_type: CloudEvents event type (overrides provider-specific extraction)
        :type ce_type: str
        :param ce_specversion: CloudEvents spec version
        :type ce_specversion: str
        :param ce_source: CloudEvents source URI
        :type ce_source: str
        :param ce_id: CloudEvents event ID
        :type ce_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._receive_webhook_serialize(
            source=source,
            request_body=request_body,
            x_hub_signature_256=x_hub_signature_256,
            stripe_signature=stripe_signature,
            x_shopify_hmac_sha256=x_shopify_hmac_sha256,
            ce_type=ce_type,
            ce_specversion=ce_specversion,
            ce_source=ce_source,
            ce_id=ce_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '200': "ReceiveWebhook200Response",
            '400': "str",
            '401': "str",
            '404': "str",
            '413': None,
            '429': None,
            '500': "str",
            '503': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _receive_webhook_serialize(
        self,
        source,
        request_body,
        x_hub_signature_256,
        stripe_signature,
        x_shopify_hmac_sha256,
        ce_type,
        ce_specversion,
        ce_source,
        ce_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if source is not None:
            _path_params['source'] = source
        # process the query parameters
        # process the header parameters
        if x_hub_signature_256 is not None:
            _header_params['X-Hub-Signature-256'] = x_hub_signature_256
        if stripe_signature is not None:
            _header_params['Stripe-Signature'] = stripe_signature
        if x_shopify_hmac_sha256 is not None:
            _header_params['X-Shopify-Hmac-SHA256'] = x_shopify_hmac_sha256
        if ce_type is not None:
            _header_params['ce-type'] = ce_type
        if ce_specversion is not None:
            _header_params['ce-specversion'] = ce_specversion
        if ce_source is not None:
            _header_params['ce-source'] = ce_source
        if ce_id is not None:
            _header_params['ce-id'] = ce_id
        # process the form parameters
        # process the body parameter
        if request_body is not None:
            _body_params = request_body


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json', 
                    'text/plain'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json', 
                        'application/octet-stream'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/webhooks/{source}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )




    @validate_call
    def send_event(
        self,
        source: Annotated[StrictStr, Field(description="Source name as defined in qhook configuration (must be type: event)")],
        event_type: Annotated[StrictStr, Field(description="Event type identifier")],
        request_body: Dict[str, Any],
        ce_type: Annotated[Optional[StrictStr], Field(description="CloudEvents event type (overrides path parameter)")] = None,
        ce_specversion: Annotated[Optional[StrictStr], Field(description="CloudEvents spec version")] = None,
        ce_source: Annotated[Optional[StrictStr], Field(description="CloudEvents source URI")] = None,
        ce_id: Annotated[Optional[StrictStr], Field(description="CloudEvents event ID")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> SendEvent202Response:
        """Send an event

        Sends an event to qhook with a source name. The source must be defined in the config as `type: event`. Multiple event sources are supported (e.g., `app`, `platform`, `billing-app`, `provisioning-app`).  If a `ce-type` header is present, it overrides the `event_type` path parameter. Requires Bearer token authentication if `api.auth_token` is configured. 

        :param source: Source name as defined in qhook configuration (must be type: event) (required)
        :type source: str
        :param event_type: Event type identifier (required)
        :type event_type: str
        :param request_body: (required)
        :type request_body: Dict[str, object]
        :param ce_type: CloudEvents event type (overrides path parameter)
        :type ce_type: str
        :param ce_specversion: CloudEvents spec version
        :type ce_specversion: str
        :param ce_source: CloudEvents source URI
        :type ce_source: str
        :param ce_id: CloudEvents event ID
        :type ce_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._send_event_serialize(
            source=source,
            event_type=event_type,
            request_body=request_body,
            ce_type=ce_type,
            ce_specversion=ce_specversion,
            ce_source=ce_source,
            ce_id=ce_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '202': "SendEvent202Response",
            '400': "str",
            '401': "str",
            '404': "str",
            '413': None,
            '429': None,
            '500': "str",
            '503': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        ).data


    @validate_call
    def send_event_with_http_info(
        self,
        source: Annotated[StrictStr, Field(description="Source name as defined in qhook configuration (must be type: event)")],
        event_type: Annotated[StrictStr, Field(description="Event type identifier")],
        request_body: Dict[str, Any],
        ce_type: Annotated[Optional[StrictStr], Field(description="CloudEvents event type (overrides path parameter)")] = None,
        ce_specversion: Annotated[Optional[StrictStr], Field(description="CloudEvents spec version")] = None,
        ce_source: Annotated[Optional[StrictStr], Field(description="CloudEvents source URI")] = None,
        ce_id: Annotated[Optional[StrictStr], Field(description="CloudEvents event ID")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> ApiResponse[SendEvent202Response]:
        """Send an event

        Sends an event to qhook with a source name. The source must be defined in the config as `type: event`. Multiple event sources are supported (e.g., `app`, `platform`, `billing-app`, `provisioning-app`).  If a `ce-type` header is present, it overrides the `event_type` path parameter. Requires Bearer token authentication if `api.auth_token` is configured. 

        :param source: Source name as defined in qhook configuration (must be type: event) (required)
        :type source: str
        :param event_type: Event type identifier (required)
        :type event_type: str
        :param request_body: (required)
        :type request_body: Dict[str, object]
        :param ce_type: CloudEvents event type (overrides path parameter)
        :type ce_type: str
        :param ce_specversion: CloudEvents spec version
        :type ce_specversion: str
        :param ce_source: CloudEvents source URI
        :type ce_source: str
        :param ce_id: CloudEvents event ID
        :type ce_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._send_event_serialize(
            source=source,
            event_type=event_type,
            request_body=request_body,
            ce_type=ce_type,
            ce_specversion=ce_specversion,
            ce_source=ce_source,
            ce_id=ce_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '202': "SendEvent202Response",
            '400': "str",
            '401': "str",
            '404': "str",
            '413': None,
            '429': None,
            '500': "str",
            '503': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        response_data.read()
        return self.api_client.response_deserialize(
            response_data=response_data,
            response_types_map=_response_types_map,
        )


    @validate_call
    def send_event_without_preload_content(
        self,
        source: Annotated[StrictStr, Field(description="Source name as defined in qhook configuration (must be type: event)")],
        event_type: Annotated[StrictStr, Field(description="Event type identifier")],
        request_body: Dict[str, Any],
        ce_type: Annotated[Optional[StrictStr], Field(description="CloudEvents event type (overrides path parameter)")] = None,
        ce_specversion: Annotated[Optional[StrictStr], Field(description="CloudEvents spec version")] = None,
        ce_source: Annotated[Optional[StrictStr], Field(description="CloudEvents source URI")] = None,
        ce_id: Annotated[Optional[StrictStr], Field(description="CloudEvents event ID")] = None,
        _request_timeout: Union[
            None,
            Annotated[StrictFloat, Field(gt=0)],
            Tuple[
                Annotated[StrictFloat, Field(gt=0)],
                Annotated[StrictFloat, Field(gt=0)]
            ]
        ] = None,
        _request_auth: Optional[Dict[StrictStr, Any]] = None,
        _content_type: Optional[StrictStr] = None,
        _headers: Optional[Dict[StrictStr, Any]] = None,
        _host_index: Annotated[StrictInt, Field(ge=0, le=0)] = 0,
    ) -> RESTResponseType:
        """Send an event

        Sends an event to qhook with a source name. The source must be defined in the config as `type: event`. Multiple event sources are supported (e.g., `app`, `platform`, `billing-app`, `provisioning-app`).  If a `ce-type` header is present, it overrides the `event_type` path parameter. Requires Bearer token authentication if `api.auth_token` is configured. 

        :param source: Source name as defined in qhook configuration (must be type: event) (required)
        :type source: str
        :param event_type: Event type identifier (required)
        :type event_type: str
        :param request_body: (required)
        :type request_body: Dict[str, object]
        :param ce_type: CloudEvents event type (overrides path parameter)
        :type ce_type: str
        :param ce_specversion: CloudEvents spec version
        :type ce_specversion: str
        :param ce_source: CloudEvents source URI
        :type ce_source: str
        :param ce_id: CloudEvents event ID
        :type ce_id: str
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :type _request_timeout: int, tuple(int, int), optional
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the
                              authentication in the spec for a single request.
        :type _request_auth: dict, optional
        :param _content_type: force content-type for the request.
        :type _content_type: str, Optional
        :param _headers: set to override the headers for a single
                         request; this effectively ignores the headers
                         in the spec for a single request.
        :type _headers: dict, optional
        :param _host_index: set to override the host_index for a single
                            request; this effectively ignores the host_index
                            in the spec for a single request.
        :type _host_index: int, optional
        :return: Returns the result object.
        """ # noqa: E501

        _param = self._send_event_serialize(
            source=source,
            event_type=event_type,
            request_body=request_body,
            ce_type=ce_type,
            ce_specversion=ce_specversion,
            ce_source=ce_source,
            ce_id=ce_id,
            _request_auth=_request_auth,
            _content_type=_content_type,
            _headers=_headers,
            _host_index=_host_index
        )

        _response_types_map: Dict[str, Optional[str]] = {
            '202': "SendEvent202Response",
            '400': "str",
            '401': "str",
            '404': "str",
            '413': None,
            '429': None,
            '500': "str",
            '503': None,
        }
        response_data = self.api_client.call_api(
            *_param,
            _request_timeout=_request_timeout
        )
        return response_data.response


    def _send_event_serialize(
        self,
        source,
        event_type,
        request_body,
        ce_type,
        ce_specversion,
        ce_source,
        ce_id,
        _request_auth,
        _content_type,
        _headers,
        _host_index,
    ) -> RequestSerialized:

        _host = None

        _collection_formats: Dict[str, str] = {
        }

        _path_params: Dict[str, str] = {}
        _query_params: List[Tuple[str, str]] = []
        _header_params: Dict[str, Optional[str]] = _headers or {}
        _form_params: List[Tuple[str, str]] = []
        _files: Dict[
            str, Union[str, bytes, List[str], List[bytes], List[Tuple[str, bytes]]]
        ] = {}
        _body_params: Optional[bytes] = None

        # process the path parameters
        if source is not None:
            _path_params['source'] = source
        if event_type is not None:
            _path_params['event_type'] = event_type
        # process the query parameters
        # process the header parameters
        if ce_type is not None:
            _header_params['ce-type'] = ce_type
        if ce_specversion is not None:
            _header_params['ce-specversion'] = ce_specversion
        if ce_source is not None:
            _header_params['ce-source'] = ce_source
        if ce_id is not None:
            _header_params['ce-id'] = ce_id
        # process the form parameters
        # process the body parameter
        if request_body is not None:
            _body_params = request_body


        # set the HTTP header `Accept`
        if 'Accept' not in _header_params:
            _header_params['Accept'] = self.api_client.select_header_accept(
                [
                    'application/json', 
                    'text/plain'
                ]
            )

        # set the HTTP header `Content-Type`
        if _content_type:
            _header_params['Content-Type'] = _content_type
        else:
            _default_content_type = (
                self.api_client.select_header_content_type(
                    [
                        'application/json', 
                        'application/cloudevents+json'
                    ]
                )
            )
            if _default_content_type is not None:
                _header_params['Content-Type'] = _default_content_type

        # authentication setting
        _auth_settings: List[str] = [
            'bearerAuth'
        ]

        return self.api_client.param_serialize(
            method='POST',
            resource_path='/events/{source}/{event_type}',
            path_params=_path_params,
            query_params=_query_params,
            header_params=_header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            auth_settings=_auth_settings,
            collection_formats=_collection_formats,
            _host=_host,
            _request_auth=_request_auth
        )


