{{- if not .Values.existingConfigMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "qhook.fullname" . }}
  labels:
    {{- include "qhook.labels" . | nindent 4 }}
data:
  qhook.yaml: |
    {{- .Values.config | toYaml | nindent 4 }}
{{- end }}
