# coding: utf-8

"""
    qhook API

    Lightweight event gateway with built-in queue, retry, and workflow engine.  qhook receives webhooks and events via HTTP, queues them, and delivers to configured handlers with retry and dead-letter support.  All responses include an `X-API-Version` header indicating the current API version. 

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qhook_client.models.get_job200_response import GetJob200Response

class TestGetJob200Response(unittest.TestCase):
    """GetJob200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetJob200Response:
        """Test GetJob200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetJob200Response`
        """
        model = GetJob200Response()
        if include_optional:
            return GetJob200Response(
                id = '',
                event_id = '',
                handler = '',
                url = '',
                status = '',
                attempt = 56,
                max_attempts = 56,
                scheduled_at = '',
                last_error = '',
                workflow_run_id = '',
                step_name = '',
                step_index = 56,
                attempts = [
                    { }
                    ]
            )
        else:
            return GetJob200Response(
                id = '',
                event_id = '',
                handler = '',
                url = '',
                status = '',
                attempt = 56,
                max_attempts = 56,
                scheduled_at = '',
        )
        """

    def testGetJob200Response(self):
        """Test GetJob200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
