# coding: utf-8

"""
    qhook API

    Lightweight event gateway with built-in queue, retry, and workflow engine.  qhook receives webhooks and events via HTTP, queues them, and delivers to configured handlers with retry and dead-letter support.  All responses include an `X-API-Version` header indicating the current API version. 

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qhook_client.api.management_api import ManagementApi


class TestManagementApi(unittest.TestCase):
    """ManagementApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ManagementApi()

    def tearDown(self) -> None:
        pass

    def test_get_event(self) -> None:
        """Test case for get_event

        Get event details
        """
        pass

    def test_get_job(self) -> None:
        """Test case for get_job

        Get job details
        """
        pass


if __name__ == '__main__':
    unittest.main()
