# coding: utf-8

"""
    qhook API

    Lightweight event gateway with built-in queue, retry, and workflow engine.  qhook receives webhooks and events via HTTP, queues them, and delivers to configured handlers with retry and dead-letter support.  All responses include an `X-API-Version` header indicating the current API version. 

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qhook_client.api.ingest_api import IngestApi


class TestIngestApi(unittest.TestCase):
    """IngestApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IngestApi()

    def tearDown(self) -> None:
        pass

    def test_receive_sns(self) -> None:
        """Test case for receive_sns

        Receive an AWS SNS message
        """
        pass

    def test_receive_webhook(self) -> None:
        """Test case for receive_webhook

        Receive a webhook
        """
        pass

    def test_send_event(self) -> None:
        """Test case for send_event

        Send an event
        """
        pass


if __name__ == '__main__':
    unittest.main()
