# coding: utf-8

"""
    qhook API

    Lightweight event gateway with built-in queue, retry, and workflow engine.  qhook receives webhooks and events via HTTP, queues them, and delivers to configured handlers with retry and dead-letter support.  All responses include an `X-API-Version` header indicating the current API version. 

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qhook_client.models.health_check503_response import HealthCheck503Response

class TestHealthCheck503Response(unittest.TestCase):
    """HealthCheck503Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> HealthCheck503Response:
        """Test HealthCheck503Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HealthCheck503Response`
        """
        model = HealthCheck503Response()
        if include_optional:
            return HealthCheck503Response(
                status = 'error',
                detail = 'database unreachable'
            )
        else:
            return HealthCheck503Response(
                status = 'error',
                detail = 'database unreachable',
        )
        """

    def testHealthCheck503Response(self):
        """Test HealthCheck503Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
