# coding: utf-8

"""
    qhook API

    Lightweight event gateway with built-in queue, retry, and workflow engine.  qhook receives webhooks and events via HTTP, queues them, and delivers to configured handlers with retry and dead-letter support.  All responses include an `X-API-Version` header indicating the current API version. 

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qhook_client.models.sns_message import SnsMessage

class TestSnsMessage(unittest.TestCase):
    """SnsMessage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SnsMessage:
        """Test SnsMessage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SnsMessage`
        """
        model = SnsMessage()
        if include_optional:
            return SnsMessage(
                type = 'Notification',
                message_id = '',
                topic_arn = '',
                subject = '',
                message = '',
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                signature = '',
                signing_cert_url = '',
                signature_version = '1',
                subscribe_url = ''
            )
        else:
            return SnsMessage(
                type = 'Notification',
                message_id = '',
                topic_arn = '',
                message = '',
                timestamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testSnsMessage(self):
        """Test SnsMessage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
