# coding: utf-8

"""
    qhook API

    Lightweight event gateway with built-in queue, retry, and workflow engine.  qhook receives webhooks and events via HTTP, queues them, and delivers to configured handlers with retry and dead-letter support.  All responses include an `X-API-Version` header indicating the current API version. 

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from qhook_client.models.get_event200_response import GetEvent200Response

class TestGetEvent200Response(unittest.TestCase):
    """GetEvent200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetEvent200Response:
        """Test GetEvent200Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetEvent200Response`
        """
        model = GetEvent200Response()
        if include_optional:
            return GetEvent200Response(
                id = '',
                source = '',
                event_type = '',
                payload = {
                    'key' : null
                    },
                headers = {
                    'key' : ''
                    },
                unique_key = '',
                created_at = '',
                jobs = [
                    { }
                    ],
                workflow_runs = [
                    { }
                    ]
            )
        else:
            return GetEvent200Response(
                id = '',
                source = '',
                event_type = '',
                payload = {
                    'key' : null
                    },
                headers = {
                    'key' : ''
                    },
                created_at = '',
                jobs = [
                    { }
                    ],
                workflow_runs = [
                    { }
                    ],
        )
        """

    def testGetEvent200Response(self):
        """Test GetEvent200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
