/* tslint:disable */
/* eslint-disable */
/**
 * qhook API
 * Lightweight event gateway with built-in queue, retry, and workflow engine.  qhook receives webhooks and events via HTTP, queues them, and delivers to configured handlers with retry and dead-letter support.  All responses include an `X-API-Version` header indicating the current API version. 
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Callback200Response
 */
export interface Callback200Response {
    /**
     * 
     * @type {string}
     * @memberof Callback200Response
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof Callback200Response
     */
    message?: string;
}

/**
 * Check if a given object implements the Callback200Response interface.
 */
export function instanceOfCallback200Response(value: object): value is Callback200Response {
    return true;
}

export function Callback200ResponseFromJSON(json: any): Callback200Response {
    return Callback200ResponseFromJSONTyped(json, false);
}

export function Callback200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): Callback200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
        'message': json['message'] == null ? undefined : json['message'],
    };
}

export function Callback200ResponseToJSON(json: any): Callback200Response {
    return Callback200ResponseToJSONTyped(json, false);
}

export function Callback200ResponseToJSONTyped(value?: Callback200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'message': value['message'],
    };
}

