/* tslint:disable */
/* eslint-disable */
/**
 * qhook API
 * Lightweight event gateway with built-in queue, retry, and workflow engine.  qhook receives webhooks and events via HTTP, queues them, and delivers to configured handlers with retry and dead-letter support.  All responses include an `X-API-Version` header indicating the current API version. 
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetEvent200Response
 */
export interface GetEvent200Response {
    /**
     * Event ULID
     * @type {string}
     * @memberof GetEvent200Response
     */
    id: string;
    /**
     * Source name
     * @type {string}
     * @memberof GetEvent200Response
     */
    source: string;
    /**
     * Event type
     * @type {string}
     * @memberof GetEvent200Response
     */
    eventType: string;
    /**
     * Event payload
     * @type {{ [key: string]: any; }}
     * @memberof GetEvent200Response
     */
    payload: { [key: string]: any; };
    /**
     * Stored headers
     * @type {{ [key: string]: string; }}
     * @memberof GetEvent200Response
     */
    headers: { [key: string]: string; };
    /**
     * Deduplication key
     * @type {string}
     * @memberof GetEvent200Response
     */
    uniqueKey?: string;
    /**
     * Creation timestamp (UTC)
     * @type {string}
     * @memberof GetEvent200Response
     */
    createdAt: string;
    /**
     * Associated jobs
     * @type {Array<{ [key: string]: any; }>}
     * @memberof GetEvent200Response
     */
    jobs: Array<{ [key: string]: any; }>;
    /**
     * Associated workflow runs
     * @type {Array<{ [key: string]: any; }>}
     * @memberof GetEvent200Response
     */
    workflowRuns: Array<{ [key: string]: any; }>;
}

/**
 * Check if a given object implements the GetEvent200Response interface.
 */
export function instanceOfGetEvent200Response(value: object): value is GetEvent200Response {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    if (!('eventType' in value) || value['eventType'] === undefined) return false;
    if (!('payload' in value) || value['payload'] === undefined) return false;
    if (!('headers' in value) || value['headers'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    if (!('jobs' in value) || value['jobs'] === undefined) return false;
    if (!('workflowRuns' in value) || value['workflowRuns'] === undefined) return false;
    return true;
}

export function GetEvent200ResponseFromJSON(json: any): GetEvent200Response {
    return GetEvent200ResponseFromJSONTyped(json, false);
}

export function GetEvent200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetEvent200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'source': json['source'],
        'eventType': json['event_type'],
        'payload': json['payload'],
        'headers': json['headers'],
        'uniqueKey': json['unique_key'] == null ? undefined : json['unique_key'],
        'createdAt': json['created_at'],
        'jobs': json['jobs'],
        'workflowRuns': json['workflow_runs'],
    };
}

export function GetEvent200ResponseToJSON(json: any): GetEvent200Response {
    return GetEvent200ResponseToJSONTyped(json, false);
}

export function GetEvent200ResponseToJSONTyped(value?: GetEvent200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'source': value['source'],
        'event_type': value['eventType'],
        'payload': value['payload'],
        'headers': value['headers'],
        'unique_key': value['uniqueKey'],
        'created_at': value['createdAt'],
        'jobs': value['jobs'],
        'workflow_runs': value['workflowRuns'],
    };
}

