/* tslint:disable */
/* eslint-disable */
/**
 * qhook API
 * Lightweight event gateway with built-in queue, retry, and workflow engine.  qhook receives webhooks and events via HTTP, queues them, and delivers to configured handlers with retry and dead-letter support.  All responses include an `X-API-Version` header indicating the current API version. 
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GetJob200Response
 */
export interface GetJob200Response {
    /**
     * Job ULID
     * @type {string}
     * @memberof GetJob200Response
     */
    id: string;
    /**
     * Associated event ULID
     * @type {string}
     * @memberof GetJob200Response
     */
    eventId: string;
    /**
     * Handler name
     * @type {string}
     * @memberof GetJob200Response
     */
    handler: string;
    /**
     * Delivery URL
     * @type {string}
     * @memberof GetJob200Response
     */
    url: string;
    /**
     * Job status
     * @type {string}
     * @memberof GetJob200Response
     */
    status: string;
    /**
     * Current attempt number
     * @type {number}
     * @memberof GetJob200Response
     */
    attempt: number;
    /**
     * Maximum retry attempts
     * @type {number}
     * @memberof GetJob200Response
     */
    maxAttempts: number;
    /**
     * Next scheduled delivery time (UTC)
     * @type {string}
     * @memberof GetJob200Response
     */
    scheduledAt: string;
    /**
     * Last delivery error message
     * @type {string}
     * @memberof GetJob200Response
     */
    lastError?: string;
    /**
     * Associated workflow run ID
     * @type {string}
     * @memberof GetJob200Response
     */
    workflowRunId?: string;
    /**
     * Workflow step name
     * @type {string}
     * @memberof GetJob200Response
     */
    stepName?: string;
    /**
     * Workflow step index
     * @type {number}
     * @memberof GetJob200Response
     */
    stepIndex?: number;
    /**
     * Delivery attempts (only if include_attempts=true)
     * @type {Array<{ [key: string]: any; }>}
     * @memberof GetJob200Response
     */
    attempts?: Array<{ [key: string]: any; }>;
}

/**
 * Check if a given object implements the GetJob200Response interface.
 */
export function instanceOfGetJob200Response(value: object): value is GetJob200Response {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('eventId' in value) || value['eventId'] === undefined) return false;
    if (!('handler' in value) || value['handler'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('attempt' in value) || value['attempt'] === undefined) return false;
    if (!('maxAttempts' in value) || value['maxAttempts'] === undefined) return false;
    if (!('scheduledAt' in value) || value['scheduledAt'] === undefined) return false;
    return true;
}

export function GetJob200ResponseFromJSON(json: any): GetJob200Response {
    return GetJob200ResponseFromJSONTyped(json, false);
}

export function GetJob200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetJob200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'eventId': json['event_id'],
        'handler': json['handler'],
        'url': json['url'],
        'status': json['status'],
        'attempt': json['attempt'],
        'maxAttempts': json['max_attempts'],
        'scheduledAt': json['scheduled_at'],
        'lastError': json['last_error'] == null ? undefined : json['last_error'],
        'workflowRunId': json['workflow_run_id'] == null ? undefined : json['workflow_run_id'],
        'stepName': json['step_name'] == null ? undefined : json['step_name'],
        'stepIndex': json['step_index'] == null ? undefined : json['step_index'],
        'attempts': json['attempts'] == null ? undefined : json['attempts'],
    };
}

export function GetJob200ResponseToJSON(json: any): GetJob200Response {
    return GetJob200ResponseToJSONTyped(json, false);
}

export function GetJob200ResponseToJSONTyped(value?: GetJob200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'event_id': value['eventId'],
        'handler': value['handler'],
        'url': value['url'],
        'status': value['status'],
        'attempt': value['attempt'],
        'max_attempts': value['maxAttempts'],
        'scheduled_at': value['scheduledAt'],
        'last_error': value['lastError'],
        'workflow_run_id': value['workflowRunId'],
        'step_name': value['stepName'],
        'step_index': value['stepIndex'],
        'attempts': value['attempts'],
    };
}

