/* tslint:disable */
/* eslint-disable */
/**
 * qhook API
 * Lightweight event gateway with built-in queue, retry, and workflow engine.  qhook receives webhooks and events via HTTP, queues them, and delivers to configured handlers with retry and dead-letter support.  All responses include an `X-API-Version` header indicating the current API version. 
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthCheck200Response
 */
export interface HealthCheck200Response {
    /**
     * 
     * @type {string}
     * @memberof HealthCheck200Response
     */
    status: string;
    /**
     * 
     * @type {number}
     * @memberof HealthCheck200Response
     */
    queueDepth: number;
}

/**
 * Check if a given object implements the HealthCheck200Response interface.
 */
export function instanceOfHealthCheck200Response(value: object): value is HealthCheck200Response {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('queueDepth' in value) || value['queueDepth'] === undefined) return false;
    return true;
}

export function HealthCheck200ResponseFromJSON(json: any): HealthCheck200Response {
    return HealthCheck200ResponseFromJSONTyped(json, false);
}

export function HealthCheck200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthCheck200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'queueDepth': json['queue_depth'],
    };
}

export function HealthCheck200ResponseToJSON(json: any): HealthCheck200Response {
    return HealthCheck200ResponseToJSONTyped(json, false);
}

export function HealthCheck200ResponseToJSONTyped(value?: HealthCheck200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'queue_depth': value['queueDepth'],
    };
}

