/* tslint:disable */
/* eslint-disable */
/**
 * qhook API
 * Lightweight event gateway with built-in queue, retry, and workflow engine.  qhook receives webhooks and events via HTTP, queues them, and delivers to configured handlers with retry and dead-letter support.  All responses include an `X-API-Version` header indicating the current API version. 
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthCheck503Response
 */
export interface HealthCheck503Response {
    /**
     * 
     * @type {string}
     * @memberof HealthCheck503Response
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof HealthCheck503Response
     */
    detail: string;
}

/**
 * Check if a given object implements the HealthCheck503Response interface.
 */
export function instanceOfHealthCheck503Response(value: object): value is HealthCheck503Response {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('detail' in value) || value['detail'] === undefined) return false;
    return true;
}

export function HealthCheck503ResponseFromJSON(json: any): HealthCheck503Response {
    return HealthCheck503ResponseFromJSONTyped(json, false);
}

export function HealthCheck503ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthCheck503Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'detail': json['detail'],
    };
}

export function HealthCheck503ResponseToJSON(json: any): HealthCheck503Response {
    return HealthCheck503ResponseToJSONTyped(json, false);
}

export function HealthCheck503ResponseToJSONTyped(value?: HealthCheck503Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
        'detail': value['detail'],
    };
}

