/* tslint:disable */
/* eslint-disable */
/**
 * qhook API
 * Lightweight event gateway with built-in queue, retry, and workflow engine.  qhook receives webhooks and events via HTTP, queues them, and delivers to configured handlers with retry and dead-letter support.  All responses include an `X-API-Version` header indicating the current API version. 
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ReceiveWebhook200Response
 */
export interface ReceiveWebhook200Response {
    /**
     * ULID of the received event
     * @type {string}
     * @memberof ReceiveWebhook200Response
     */
    eventId: string;
    /**
     * Whether the event was a duplicate
     * @type {boolean}
     * @memberof ReceiveWebhook200Response
     */
    duplicate: boolean;
    /**
     * Number of jobs created for this event
     * @type {number}
     * @memberof ReceiveWebhook200Response
     */
    jobsCreated: number;
}

/**
 * Check if a given object implements the ReceiveWebhook200Response interface.
 */
export function instanceOfReceiveWebhook200Response(value: object): value is ReceiveWebhook200Response {
    if (!('eventId' in value) || value['eventId'] === undefined) return false;
    if (!('duplicate' in value) || value['duplicate'] === undefined) return false;
    if (!('jobsCreated' in value) || value['jobsCreated'] === undefined) return false;
    return true;
}

export function ReceiveWebhook200ResponseFromJSON(json: any): ReceiveWebhook200Response {
    return ReceiveWebhook200ResponseFromJSONTyped(json, false);
}

export function ReceiveWebhook200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ReceiveWebhook200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'eventId': json['event_id'],
        'duplicate': json['duplicate'],
        'jobsCreated': json['jobs_created'],
    };
}

export function ReceiveWebhook200ResponseToJSON(json: any): ReceiveWebhook200Response {
    return ReceiveWebhook200ResponseToJSONTyped(json, false);
}

export function ReceiveWebhook200ResponseToJSONTyped(value?: ReceiveWebhook200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event_id': value['eventId'],
        'duplicate': value['duplicate'],
        'jobs_created': value['jobsCreated'],
    };
}

