/* tslint:disable */
/* eslint-disable */
/**
 * qhook API
 * Lightweight event gateway with built-in queue, retry, and workflow engine.  qhook receives webhooks and events via HTTP, queues them, and delivers to configured handlers with retry and dead-letter support.  All responses include an `X-API-Version` header indicating the current API version. 
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendEventRequest
 */
export interface SendEventRequest {
    /**
     * 
     * @type {string}
     * @memberof SendEventRequest
     */
    specversion: string;
    /**
     * 
     * @type {string}
     * @memberof SendEventRequest
     */
    type: string;
    /**
     * 
     * @type {string}
     * @memberof SendEventRequest
     */
    source: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof SendEventRequest
     */
    data?: { [key: string]: any; };
}

/**
 * Check if a given object implements the SendEventRequest interface.
 */
export function instanceOfSendEventRequest(value: object): value is SendEventRequest {
    if (!('specversion' in value) || value['specversion'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('source' in value) || value['source'] === undefined) return false;
    return true;
}

export function SendEventRequestFromJSON(json: any): SendEventRequest {
    return SendEventRequestFromJSONTyped(json, false);
}

export function SendEventRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendEventRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'specversion': json['specversion'],
        'type': json['type'],
        'source': json['source'],
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function SendEventRequestToJSON(json: any): SendEventRequest {
    return SendEventRequestToJSONTyped(json, false);
}

export function SendEventRequestToJSONTyped(value?: SendEventRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'specversion': value['specversion'],
        'type': value['type'],
        'source': value['source'],
        'data': value['data'],
    };
}

