/* tslint:disable */
/* eslint-disable */
/**
 * qhook API
 * Lightweight event gateway with built-in queue, retry, and workflow engine.  qhook receives webhooks and events via HTTP, queues them, and delivers to configured handlers with retry and dead-letter support.  All responses include an `X-API-Version` header indicating the current API version. 
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SendEvent202Response
 */
export interface SendEvent202Response {
    /**
     * ULID of the accepted event
     * @type {string}
     * @memberof SendEvent202Response
     */
    eventId: string;
    /**
     * Number of jobs created for this event
     * @type {number}
     * @memberof SendEvent202Response
     */
    jobsCreated: number;
}

/**
 * Check if a given object implements the SendEvent202Response interface.
 */
export function instanceOfSendEvent202Response(value: object): value is SendEvent202Response {
    if (!('eventId' in value) || value['eventId'] === undefined) return false;
    if (!('jobsCreated' in value) || value['jobsCreated'] === undefined) return false;
    return true;
}

export function SendEvent202ResponseFromJSON(json: any): SendEvent202Response {
    return SendEvent202ResponseFromJSONTyped(json, false);
}

export function SendEvent202ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SendEvent202Response {
    if (json == null) {
        return json;
    }
    return {
        
        'eventId': json['event_id'],
        'jobsCreated': json['jobs_created'],
    };
}

export function SendEvent202ResponseToJSON(json: any): SendEvent202Response {
    return SendEvent202ResponseToJSONTyped(json, false);
}

export function SendEvent202ResponseToJSONTyped(value?: SendEvent202Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'event_id': value['eventId'],
        'jobs_created': value['jobsCreated'],
    };
}

