/* tslint:disable */
/* eslint-disable */
/**
 * qhook API
 * Lightweight event gateway with built-in queue, retry, and workflow engine.  qhook receives webhooks and events via HTTP, queues them, and delivers to configured handlers with retry and dead-letter support.  All responses include an `X-API-Version` header indicating the current API version. 
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SnsMessage
 */
export interface SnsMessage {
    /**
     * 
     * @type {SnsMessageTypeEnum}
     * @memberof SnsMessage
     */
    type: SnsMessageTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof SnsMessage
     */
    messageId: string;
    /**
     * 
     * @type {string}
     * @memberof SnsMessage
     */
    topicArn: string;
    /**
     * 
     * @type {string}
     * @memberof SnsMessage
     */
    subject?: string;
    /**
     * The actual payload (JSON string for Notification)
     * @type {string}
     * @memberof SnsMessage
     */
    message: string;
    /**
     * 
     * @type {Date}
     * @memberof SnsMessage
     */
    timestamp: Date;
    /**
     * 
     * @type {string}
     * @memberof SnsMessage
     */
    signature?: string;
    /**
     * 
     * @type {string}
     * @memberof SnsMessage
     */
    signingCertURL?: string;
    /**
     * 
     * @type {SnsMessageSignatureVersionEnum}
     * @memberof SnsMessage
     */
    signatureVersion?: SnsMessageSignatureVersionEnum;
    /**
     * Present only for SubscriptionConfirmation
     * @type {string}
     * @memberof SnsMessage
     */
    subscribeURL?: string;
}


/**
 * @export
 */
export const SnsMessageTypeEnum = {
    Notification: 'Notification',
    SubscriptionConfirmation: 'SubscriptionConfirmation',
    UnsubscribeConfirmation: 'UnsubscribeConfirmation'
} as const;
export type SnsMessageTypeEnum = typeof SnsMessageTypeEnum[keyof typeof SnsMessageTypeEnum];

/**
 * @export
 */
export const SnsMessageSignatureVersionEnum = {
    _1: '1',
    _2: '2'
} as const;
export type SnsMessageSignatureVersionEnum = typeof SnsMessageSignatureVersionEnum[keyof typeof SnsMessageSignatureVersionEnum];


/**
 * Check if a given object implements the SnsMessage interface.
 */
export function instanceOfSnsMessage(value: object): value is SnsMessage {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('messageId' in value) || value['messageId'] === undefined) return false;
    if (!('topicArn' in value) || value['topicArn'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function SnsMessageFromJSON(json: any): SnsMessage {
    return SnsMessageFromJSONTyped(json, false);
}

export function SnsMessageFromJSONTyped(json: any, ignoreDiscriminator: boolean): SnsMessage {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['Type'],
        'messageId': json['MessageId'],
        'topicArn': json['TopicArn'],
        'subject': json['Subject'] == null ? undefined : json['Subject'],
        'message': json['Message'],
        'timestamp': (new Date(json['Timestamp'])),
        'signature': json['Signature'] == null ? undefined : json['Signature'],
        'signingCertURL': json['SigningCertURL'] == null ? undefined : json['SigningCertURL'],
        'signatureVersion': json['SignatureVersion'] == null ? undefined : json['SignatureVersion'],
        'subscribeURL': json['SubscribeURL'] == null ? undefined : json['SubscribeURL'],
    };
}

export function SnsMessageToJSON(json: any): SnsMessage {
    return SnsMessageToJSONTyped(json, false);
}

export function SnsMessageToJSONTyped(value?: SnsMessage | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'Type': value['type'],
        'MessageId': value['messageId'],
        'TopicArn': value['topicArn'],
        'Subject': value['subject'],
        'Message': value['message'],
        'Timestamp': value['timestamp'].toISOString(),
        'Signature': value['signature'],
        'SigningCertURL': value['signingCertURL'],
        'SignatureVersion': value['signatureVersion'],
        'SubscribeURL': value['subscribeURL'],
    };
}

