/* tslint:disable */
/* eslint-disable */
/**
 * qhook API
 * Lightweight event gateway with built-in queue, retry, and workflow engine.  qhook receives webhooks and events via HTTP, queues them, and delivers to configured handlers with retry and dead-letter support.  All responses include an `X-API-Version` header indicating the current API version. 
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Callback200Response,
} from '../models/index';
import {
    Callback200ResponseFromJSON,
    Callback200ResponseToJSON,
} from '../models/index';

export interface CallbackRequest {
    token: string;
    requestBody: { [key: string]: any; };
}

/**
 * 
 */
export class CallbackApi extends runtime.BaseAPI {

    /**
     * Creates request options for callback without sending the request
     */
    async callbackRequestOpts(requestParameters: CallbackRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['token'] == null) {
            throw new runtime.RequiredError(
                'token',
                'Required parameter "token" was null or undefined when calling callback().'
            );
        }

        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling callback().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/callback/{token}`;
        urlPath = urlPath.replace(`{${"token"}}`, encodeURIComponent(String(requestParameters['token'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        };
    }

    /**
     * Resumes a workflow step that is waiting for a callback. The token is a cryptographic identifier generated when the callback step was created.  The request body becomes the step output, available to subsequent steps via response chaining.  Returns a uniform 404 for all failure cases (invalid, expired, or already-used tokens) to prevent token enumeration. 
     * Resume a waiting workflow step
     */
    async callbackRaw(requestParameters: CallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Callback200Response>> {
        const requestOptions = await this.callbackRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => Callback200ResponseFromJSON(jsonValue));
    }

    /**
     * Resumes a workflow step that is waiting for a callback. The token is a cryptographic identifier generated when the callback step was created.  The request body becomes the step output, available to subsequent steps via response chaining.  Returns a uniform 404 for all failure cases (invalid, expired, or already-used tokens) to prevent token enumeration. 
     * Resume a waiting workflow step
     */
    async callback(requestParameters: CallbackRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Callback200Response> {
        const response = await this.callbackRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
