/* tslint:disable */
/* eslint-disable */
/**
 * qhook API
 * Lightweight event gateway with built-in queue, retry, and workflow engine.  qhook receives webhooks and events via HTTP, queues them, and delivers to configured handlers with retry and dead-letter support.  All responses include an `X-API-Version` header indicating the current API version. 
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ReceiveWebhook200Response,
  SendEvent202Response,
  SendEventRequest,
  SnsMessage,
} from '../models/index';
import {
    ReceiveWebhook200ResponseFromJSON,
    ReceiveWebhook200ResponseToJSON,
    SendEvent202ResponseFromJSON,
    SendEvent202ResponseToJSON,
    SendEventRequestFromJSON,
    SendEventRequestToJSON,
    SnsMessageFromJSON,
    SnsMessageToJSON,
} from '../models/index';

export interface ReceiveSnsRequest {
    source: string;
    snsMessage: SnsMessage;
}

export interface ReceiveWebhookRequest {
    source: string;
    requestBody: { [key: string]: any; };
    xHubSignature256?: string;
    stripeSignature?: string;
    xShopifyHmacSHA256?: string;
    ceType?: string;
    ceSpecversion?: string;
    ceSource?: string;
    ceId?: string;
}

export interface SendEventOperationRequest {
    source: string;
    eventType: string;
    requestBody: { [key: string]: any; };
    ceType?: string;
    ceSpecversion?: string;
    ceSource?: string;
    ceId?: string;
}

/**
 * 
 */
export class IngestApi extends runtime.BaseAPI {

    /**
     * Creates request options for receiveSns without sending the request
     */
    async receiveSnsRequestOpts(requestParameters: ReceiveSnsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['source'] == null) {
            throw new runtime.RequiredError(
                'source',
                'Required parameter "source" was null or undefined when calling receiveSns().'
            );
        }

        if (requestParameters['snsMessage'] == null) {
            throw new runtime.RequiredError(
                'snsMessage',
                'Required parameter "snsMessage" was null or undefined when calling receiveSns().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/sns/{source}`;
        urlPath = urlPath.replace(`{${"source"}}`, encodeURIComponent(String(requestParameters['source'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SnsMessageToJSON(requestParameters['snsMessage']),
        };
    }

    /**
     * Receives AWS SNS messages (Notification, SubscriptionConfirmation, UnsubscribeConfirmation). Subscription confirmations are auto-confirmed. Notification payloads are unwrapped from the SNS envelope and processed as events.  X.509 signature verification is performed unless `skip_verify: true` is set on the source. 
     * Receive an AWS SNS message
     */
    async receiveSnsRaw(requestParameters: ReceiveSnsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const requestOptions = await this.receiveSnsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Receives AWS SNS messages (Notification, SubscriptionConfirmation, UnsubscribeConfirmation). Subscription confirmations are auto-confirmed. Notification payloads are unwrapped from the SNS envelope and processed as events.  X.509 signature verification is performed unless `skip_verify: true` is set on the source. 
     * Receive an AWS SNS message
     */
    async receiveSns(requestParameters: ReceiveSnsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.receiveSnsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for receiveWebhook without sending the request
     */
    async receiveWebhookRequestOpts(requestParameters: ReceiveWebhookRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['source'] == null) {
            throw new runtime.RequiredError(
                'source',
                'Required parameter "source" was null or undefined when calling receiveWebhook().'
            );
        }

        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling receiveWebhook().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['xHubSignature256'] != null) {
            headerParameters['X-Hub-Signature-256'] = String(requestParameters['xHubSignature256']);
        }

        if (requestParameters['stripeSignature'] != null) {
            headerParameters['Stripe-Signature'] = String(requestParameters['stripeSignature']);
        }

        if (requestParameters['xShopifyHmacSHA256'] != null) {
            headerParameters['X-Shopify-Hmac-SHA256'] = String(requestParameters['xShopifyHmacSHA256']);
        }

        if (requestParameters['ceType'] != null) {
            headerParameters['ce-type'] = String(requestParameters['ceType']);
        }

        if (requestParameters['ceSpecversion'] != null) {
            headerParameters['ce-specversion'] = String(requestParameters['ceSpecversion']);
        }

        if (requestParameters['ceSource'] != null) {
            headerParameters['ce-source'] = String(requestParameters['ceSource']);
        }

        if (requestParameters['ceId'] != null) {
            headerParameters['ce-id'] = String(requestParameters['ceId']);
        }


        let urlPath = `/webhooks/{source}`;
        urlPath = urlPath.replace(`{${"source"}}`, encodeURIComponent(String(requestParameters['source'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        };
    }

    /**
     * Receives a webhook payload from an external provider (e.g. GitHub, Stripe, Shopify). Signature verification is performed if configured for the source.  **Event type extraction order:** 1. `ce-type` header (CloudEvents binary mode) 2. `type` field in JSON body (CloudEvents structured mode) 3. Provider-specific logic (Stripe `$.type`, GitHub `$.action`, Shopify `$.topic`) 4. Fallback: `\"event\"` 
     * Receive a webhook
     */
    async receiveWebhookRaw(requestParameters: ReceiveWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ReceiveWebhook200Response>> {
        const requestOptions = await this.receiveWebhookRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ReceiveWebhook200ResponseFromJSON(jsonValue));
    }

    /**
     * Receives a webhook payload from an external provider (e.g. GitHub, Stripe, Shopify). Signature verification is performed if configured for the source.  **Event type extraction order:** 1. `ce-type` header (CloudEvents binary mode) 2. `type` field in JSON body (CloudEvents structured mode) 3. Provider-specific logic (Stripe `$.type`, GitHub `$.action`, Shopify `$.topic`) 4. Fallback: `\"event\"` 
     * Receive a webhook
     */
    async receiveWebhook(requestParameters: ReceiveWebhookRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ReceiveWebhook200Response> {
        const response = await this.receiveWebhookRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for sendEvent without sending the request
     */
    async sendEventRequestOpts(requestParameters: SendEventOperationRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['source'] == null) {
            throw new runtime.RequiredError(
                'source',
                'Required parameter "source" was null or undefined when calling sendEvent().'
            );
        }

        if (requestParameters['eventType'] == null) {
            throw new runtime.RequiredError(
                'eventType',
                'Required parameter "eventType" was null or undefined when calling sendEvent().'
            );
        }

        if (requestParameters['requestBody'] == null) {
            throw new runtime.RequiredError(
                'requestBody',
                'Required parameter "requestBody" was null or undefined when calling sendEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['ceType'] != null) {
            headerParameters['ce-type'] = String(requestParameters['ceType']);
        }

        if (requestParameters['ceSpecversion'] != null) {
            headerParameters['ce-specversion'] = String(requestParameters['ceSpecversion']);
        }

        if (requestParameters['ceSource'] != null) {
            headerParameters['ce-source'] = String(requestParameters['ceSource']);
        }

        if (requestParameters['ceId'] != null) {
            headerParameters['ce-id'] = String(requestParameters['ceId']);
        }

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/events/{source}/{event_type}`;
        urlPath = urlPath.replace(`{${"source"}}`, encodeURIComponent(String(requestParameters['source'])));
        urlPath = urlPath.replace(`{${"event_type"}}`, encodeURIComponent(String(requestParameters['eventType'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['requestBody'],
        };
    }

    /**
     * Sends an event to qhook with a source name. The source must be defined in the config as `type: event`. Multiple event sources are supported (e.g., `app`, `platform`, `billing-app`, `provisioning-app`).  If a `ce-type` header is present, it overrides the `event_type` path parameter. Requires Bearer token authentication if `api.auth_token` is configured. 
     * Send an event
     */
    async sendEventRaw(requestParameters: SendEventOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SendEvent202Response>> {
        const requestOptions = await this.sendEventRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SendEvent202ResponseFromJSON(jsonValue));
    }

    /**
     * Sends an event to qhook with a source name. The source must be defined in the config as `type: event`. Multiple event sources are supported (e.g., `app`, `platform`, `billing-app`, `provisioning-app`).  If a `ce-type` header is present, it overrides the `event_type` path parameter. Requires Bearer token authentication if `api.auth_token` is configured. 
     * Send an event
     */
    async sendEvent(requestParameters: SendEventOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SendEvent202Response> {
        const response = await this.sendEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
