/* tslint:disable */
/* eslint-disable */
/**
 * qhook API
 * Lightweight event gateway with built-in queue, retry, and workflow engine.  qhook receives webhooks and events via HTTP, queues them, and delivers to configured handlers with retry and dead-letter support.  All responses include an `X-API-Version` header indicating the current API version. 
 *
 * The version of the OpenAPI document: 0.4.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  GetEvent200Response,
  GetJob200Response,
} from '../models/index';
import {
    GetEvent200ResponseFromJSON,
    GetEvent200ResponseToJSON,
    GetJob200ResponseFromJSON,
    GetJob200ResponseToJSON,
} from '../models/index';

export interface GetEventRequest {
    eventId: string;
}

export interface GetJobRequest {
    jobId: string;
    includeAttempts?: boolean;
}

/**
 * 
 */
export class ManagementApi extends runtime.BaseAPI {

    /**
     * Creates request options for getEvent without sending the request
     */
    async getEventRequestOpts(requestParameters: GetEventRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['eventId'] == null) {
            throw new runtime.RequiredError(
                'eventId',
                'Required parameter "eventId" was null or undefined when calling getEvent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/events/{event_id}`;
        urlPath = urlPath.replace(`{${"event_id"}}`, encodeURIComponent(String(requestParameters['eventId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns event details including associated jobs and workflow runs. Requires Bearer token authentication if `api.auth_token` is configured. 
     * Get event details
     */
    async getEventRaw(requestParameters: GetEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetEvent200Response>> {
        const requestOptions = await this.getEventRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetEvent200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns event details including associated jobs and workflow runs. Requires Bearer token authentication if `api.auth_token` is configured. 
     * Get event details
     */
    async getEvent(requestParameters: GetEventRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetEvent200Response> {
        const response = await this.getEventRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getJob without sending the request
     */
    async getJobRequestOpts(requestParameters: GetJobRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['jobId'] == null) {
            throw new runtime.RequiredError(
                'jobId',
                'Required parameter "jobId" was null or undefined when calling getJob().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['includeAttempts'] != null) {
            queryParameters['include_attempts'] = requestParameters['includeAttempts'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearerAuth", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/api/jobs/{job_id}`;
        urlPath = urlPath.replace(`{${"job_id"}}`, encodeURIComponent(String(requestParameters['jobId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns job details including workflow data. Optionally includes delivery attempts. Requires Bearer token authentication if `api.auth_token` is configured. 
     * Get job details
     */
    async getJobRaw(requestParameters: GetJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<GetJob200Response>> {
        const requestOptions = await this.getJobRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => GetJob200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns job details including workflow data. Optionally includes delivery attempts. Requires Bearer token authentication if `api.auth_token` is configured. 
     * Get job details
     */
    async getJob(requestParameters: GetJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<GetJob200Response> {
        const response = await this.getJobRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
