# coding: utf-8

"""
    qhook API

    Lightweight event gateway with built-in queue, retry, and workflow engine.  qhook receives webhooks and events via HTTP, queues them, and delivers to configured handlers with retry and dead-letter support.  All responses include an `X-API-Version` header indicating the current API version. 

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class GetEvent200Response(BaseModel):
    """
    GetEvent200Response
    """ # noqa: E501
    id: StrictStr = Field(description="Event ULID")
    source: StrictStr = Field(description="Source name")
    event_type: StrictStr = Field(description="Event type")
    payload: Dict[str, Any] = Field(description="Event payload")
    headers: Dict[str, StrictStr] = Field(description="Stored headers")
    unique_key: Optional[StrictStr] = Field(default=None, description="Deduplication key")
    created_at: StrictStr = Field(description="Creation timestamp (UTC)")
    jobs: List[Dict[str, Any]] = Field(description="Associated jobs")
    workflow_runs: List[Dict[str, Any]] = Field(description="Associated workflow runs")
    __properties: ClassVar[List[str]] = ["id", "source", "event_type", "payload", "headers", "unique_key", "created_at", "jobs", "workflow_runs"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetEvent200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetEvent200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "source": obj.get("source"),
            "event_type": obj.get("event_type"),
            "payload": obj.get("payload"),
            "headers": obj.get("headers"),
            "unique_key": obj.get("unique_key"),
            "created_at": obj.get("created_at"),
            "jobs": obj.get("jobs"),
            "workflow_runs": obj.get("workflow_runs")
        })
        return _obj


