# coding: utf-8

"""
    qhook API

    Lightweight event gateway with built-in queue, retry, and workflow engine.  qhook receives webhooks and events via HTTP, queues them, and delivers to configured handlers with retry and dead-letter support.  All responses include an `X-API-Version` header indicating the current API version. 

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class GetJob200Response(BaseModel):
    """
    GetJob200Response
    """ # noqa: E501
    id: StrictStr = Field(description="Job ULID")
    event_id: StrictStr = Field(description="Associated event ULID")
    handler: StrictStr = Field(description="Handler name")
    url: StrictStr = Field(description="Delivery URL")
    status: StrictStr = Field(description="Job status")
    attempt: StrictInt = Field(description="Current attempt number")
    max_attempts: StrictInt = Field(description="Maximum retry attempts")
    scheduled_at: StrictStr = Field(description="Next scheduled delivery time (UTC)")
    last_error: Optional[StrictStr] = Field(default=None, description="Last delivery error message")
    workflow_run_id: Optional[StrictStr] = Field(default=None, description="Associated workflow run ID")
    step_name: Optional[StrictStr] = Field(default=None, description="Workflow step name")
    step_index: Optional[StrictInt] = Field(default=None, description="Workflow step index")
    attempts: Optional[List[Dict[str, Any]]] = Field(default=None, description="Delivery attempts (only if include_attempts=true)")
    __properties: ClassVar[List[str]] = ["id", "event_id", "handler", "url", "status", "attempt", "max_attempts", "scheduled_at", "last_error", "workflow_run_id", "step_name", "step_index", "attempts"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GetJob200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GetJob200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "event_id": obj.get("event_id"),
            "handler": obj.get("handler"),
            "url": obj.get("url"),
            "status": obj.get("status"),
            "attempt": obj.get("attempt"),
            "max_attempts": obj.get("max_attempts"),
            "scheduled_at": obj.get("scheduled_at"),
            "last_error": obj.get("last_error"),
            "workflow_run_id": obj.get("workflow_run_id"),
            "step_name": obj.get("step_name"),
            "step_index": obj.get("step_index"),
            "attempts": obj.get("attempts")
        })
        return _obj


