# coding: utf-8

"""
    qhook API

    Lightweight event gateway with built-in queue, retry, and workflow engine.  qhook receives webhooks and events via HTTP, queues them, and delivers to configured handlers with retry and dead-letter support.  All responses include an `X-API-Version` header indicating the current API version. 

    The version of the OpenAPI document: 0.4.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SnsMessage(BaseModel):
    """
    SnsMessage
    """ # noqa: E501
    type: StrictStr = Field(alias="Type")
    message_id: StrictStr = Field(alias="MessageId")
    topic_arn: StrictStr = Field(alias="TopicArn")
    subject: Optional[StrictStr] = Field(default=None, alias="Subject")
    message: StrictStr = Field(description="The actual payload (JSON string for Notification)", alias="Message")
    timestamp: datetime = Field(alias="Timestamp")
    signature: Optional[StrictStr] = Field(default=None, alias="Signature")
    signing_cert_url: Optional[StrictStr] = Field(default=None, alias="SigningCertURL")
    signature_version: Optional[StrictStr] = Field(default=None, alias="SignatureVersion")
    subscribe_url: Optional[StrictStr] = Field(default=None, description="Present only for SubscriptionConfirmation", alias="SubscribeURL")
    __properties: ClassVar[List[str]] = ["Type", "MessageId", "TopicArn", "Subject", "Message", "Timestamp", "Signature", "SigningCertURL", "SignatureVersion", "SubscribeURL"]

    @field_validator('type')
    def type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['Notification', 'SubscriptionConfirmation', 'UnsubscribeConfirmation']):
            raise ValueError("must be one of enum values ('Notification', 'SubscriptionConfirmation', 'UnsubscribeConfirmation')")
        return value

    @field_validator('signature_version')
    def signature_version_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['1', '2']):
            raise ValueError("must be one of enum values ('1', '2')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SnsMessage from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SnsMessage from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "Type": obj.get("Type"),
            "MessageId": obj.get("MessageId"),
            "TopicArn": obj.get("TopicArn"),
            "Subject": obj.get("Subject"),
            "Message": obj.get("Message"),
            "Timestamp": obj.get("Timestamp"),
            "Signature": obj.get("Signature"),
            "SigningCertURL": obj.get("SigningCertURL"),
            "SignatureVersion": obj.get("SignatureVersion"),
            "SubscribeURL": obj.get("SubscribeURL")
        })
        return _obj


